### ISSUE TITLE
Cant run the tool

### ISSUE THREAD

**Issue by Abwart** [Xeift/Metamask-Mnemonic-Brute-Force#1]
Entered the Alchemy apikey like this:
`const api = process.env['ulTLkWD39XxXxXxXxXxXxXxXxFcTkgCF']// web3 provider api`
![t6UcPGNusP](https://user-images.githubusercontent.com/101443682/162598974-e14f0e23-735c-4fd3-bf93-3be94e4daf21.png)

What am I doing wrong?

**Comment by Xeift** [comment]
change `process.env['abc']` to your web3 provider api url
you can put url in environment variable if you want to run it in repl.it
![image](https://user-images.githubusercontent.com/80938768/162602284-eed5373b-f909-4c6d-adff-9ea80bce80f2.png)

**Comment by Abwart** [comment]
So I changed line 4 to:
`const api = process.env['https://eth-mainnet.alchemyapi.io/v2/ulTLkWD39XxXxXxXxXxXxXxXxFcTkgCF']// web3 provider api`
but I still receive the same error?
needed npm modules are installed btw.

**Comment by Abwart** [comment]
Got it working. My mistake. :)
